name: Build

on:
  push:
    paths:
      - "**.gradle"
      - "**.properties"
      - "**.java"
      - "**.toml"
      - "**.xml"
      - ".github/workflows/*.yml"
    branches:
      - "**"
  pull_request:
    branches:
      - master
jobs:
  fullbuild:
    runs-on: ubuntu-latest

    name: Java 20 build
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: JDK Setup
        uses: actions/setup-java@v3.13.0
        with:
          distribution: temurin
          java-version: 20

      - name: D-BUS AT-SPI Installation
        run: sudo apt-get -y install at-spi2-core

      - name: Build
        id: build
        uses: gradle/gradle-build-action@v2.9.0
        with:
          arguments: |
            build
            -PskipSpotless
        continue-on-error: true

      - name: Test
        id: test
        uses: coactions/setup-xvfb@v1.0.1
        with:
          run: ./gradlew jacocoTestReport -PskipSpotless
        continue-on-error: true

      - name: Prepare Email Content
        run: |
            BUILD_STATUS=true
            TEST_STATUS=true
            if [ "${{ steps.build.outcome }}" == "failure" ]; then
              BUILD_STATUS=false
            fi
            if [ "${{ steps.test.outcome }}" == "failure" ]; then
              TEST_STATUS=false
            fi
            echo "BUILD_STATUS=${BUILD_STATUS}" >> $GITHUB_ENV
            echo "TEST_STATUS=${TEST_STATUS}" >> $GITHUB_ENV

      # Debug: Print the environment variables to the log
      - name: Debug Environment Variables
        run: |
          echo "Build status from env: $BUILD_STATUS"
          echo "Test status from env: $TEST_STATUS"



      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          secure: false  # Use STARTTLS, which starts unsecured and then  switches to a secure connection
          username: ${{ secrets.OUTLOOK_USERNAME }}
          password: ${{ secrets.OUTLOOK_PASSWORD }}
          subject: Build and Test Results for ${{ github.repository }}
          to: collegeforpete@gmail.com
          from: "LitiEngine Team 2 <${{ secrets.OUTLOOK_USERNAME }}>"
          cc: pmettaprasert@seattleu.edu
          body: |
            Build Status Successful: ${{ env.BUILD_STATUS }}
            Test Status Successful: ${{ env.TEST_STATUS }}
        continue-on-error: true


      - name: Package Creation
        uses: gradle/gradle-build-action@v2.9.0
        with:
          arguments: jpackage

            # - name: Static Analysis
            #   uses: gradle/gradle-build-action@v2.9.0
            #   env:
            #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            #   if: ${{!github.event.pull_request.head.repo.fork}}
            #   with:
          #     arguments: |
          #       sonar
          #       -PskipSpotless


      - name: Code Style Validation
        uses: gradle/gradle-build-action@v2.9.0
        with:
          arguments: spotlessCheck
